# .github/workflows/pr-build.yml
name: Build on PR

on:
  pull_request:
    branches:
      - master  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Or `yarn install` if you use Yarn

      - name: Build project
        run: npm run build  # Or `yarn build` if you use Yarn

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build  # Path to the build output directory
